blueprints/home.py
from flask import Blueprint, render_template, redirect, url_for, request

home = Blueprint('home', __name__)

@home.route('/')
def home_page():
    return render_template('home/index.html')

@home.route('/lookup', methods=['POST'])
def lookup():
    print(request.form)
    return redirect(url_for('stock.quote', ticker=request.form['ticker']))

blueprints/stock.py
from flask import Blueprint, render_template
import requests

stock = Blueprint('stock', __name__)

def fetch_price(ticker):
    data = requests.get(f'https://financialmodelingprep.com/api/v3/stock/real-time-price/{ticker}', params={'apikey': 'd6cd75b36a0c9a4c6ad1a038177b6ea3'}).json()
    
    return data["price"]

def fetch_income(ticker):
    financials = requests.get(f'https://financialmodelingprep.com/api/v3/financials/income-statement/{ticker}', params={'period': 'quarter', 'apikey': 'd6cd75b36a0c9a4c6ad1a038177b6ea3'}).json()["financials"]
    financials.sort(key=lambda quarter: quarter["date"])
    return financials

@stock.route('/<string:ticker>')
def quote(ticker):
    price = fetch_price(ticker)
    return render_template('stock/quote.html', ticker = ticker, stock_price = price)

@stock.route('/<string:ticker>/financials')
def financials(ticker):
    data = fetch_income(ticker)

    chart_data = [float(q["EPS"]) for q in data if q["EPS"]]
    chart_params = {"type": 'line',
                    "data": {
                        'labels': [q["date"] for q in data if q["EPS"]],
                        'datasets': [{'label': 'EPS', 'data': chart_data}]
                    }}




    return render_template('stock/financials.html', ticker = ticker, financials = data, chart_params = chart_params)

templates/base_layout.html
<html>
    <head>
        <title>{% block title %}View Stock Prices{% endblock %} - Stock App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a href="{{ url_for('home.home_page') }}" class="navbar-brand"> Stock App </a>
            <ul class="navbar-nav me-auto">
                <li class="nav-item">   
                    <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
                </li>
            </ul>
            <form class="form-inline" method="POST" action="{{ url_for('home.lookup') }}">
                <input class="form-control mr-sm-2" type="input" name="ticker" placeholder="Enter Stock Symbol" aria-label="Lookup">
                <button class="btn btn-outline-success my-2 my-sm-2" type="submit">Lookup</button>   
            </form>
        </nav>

        <div class="container mt-3">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/home/index.html
{% extends "base_layout.html" %}
{% block title %} Home Page {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm">
        <h1>Welcome to StockApp</h1>
        <div>This is a quick way to view the price of stocks</div>
    </div>
    <div class="col">
        {% include 'shared/portfolio.html' %}
    </div>
</div>
{% endblock %}
        

templates/shared/portfolio.html
<h2> Your portfolio: </h2>
<ul>
    {% for ticker in ['AAPL', 'GOOGL', 'FB', 'TSLA'] %}
        <li> <a href="{{ url_for('stock.quote', ticker=ticker) }}">View {{ ticker }}</a> </li>
    {% endfor %}    
</ul>
    

templates/stock/financials.html
{% extends "base_layout.html" %}
{% block title %} {{ ticker }} Financials {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
           <img src="https://quickchart.io/chart?width=500&height=200&c={{ chart_params }}" />
        </div>
        <table class="table mt-4">
            <thead>
                <tr>
                    <th scope="col">As of</th>
                    <th scope="col">Revenue</th>
                    <th scope="col">Gross Margin</th>
                    <th scope="col">EPS</th>
                </tr>
            </thead>
            <tbody>
                {% for quarter in financials | reverse %}
                <tr>
                    <th scope="row">{{ quarter["date"] }}</th>
                    <td>{{ "${:,.0f}".format(quarter["Revenue"] | float) }}</td>
                    <td>{{ ((quarter["Gross Margin"] | float) * 100) | round(2) }}%</td>
                    <td>${{ quarter["EPS"] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/stock/quote.html
{% extends "base_layout.html" %}
{% block title %} {{ ticker }} Stock Quote {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm">
        <h1 class="mb-3">{{ ticker }}</h1>
        <hr />
        <h2>Price: ${{ stock_price }}</h2>
    </div>
    <div class="col">
        {% include 'shared/portfolio.html' %}
    </div>
</div>
{% endblock %}